PORTNAME=	bsdinfo
DISTVERSION=	0.30
CATEGORIES=	sysutils

MAINTAINER=	s@samu.pl
COMMENT=	Simple utility to display system-based information
WWW=		https://github.com/ceri/bsdinfo

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	ceri
GH_PROJECT=	bsdinfo
GH_TAGNAME=	d355dad

PLIST_FILES=	bin/bsdinfo \
		bin/bsdinfon

.include <bsd.port.mk>
