PORTNAME=	bsdinfo
DISTVERSION=	0.32
CATEGORIES=	sysutils

MAINTAINER=	s@samu.pl
COMMENT=	Simple utility to display system-based information
WWW=		https://github.com/ceri/bsdinfo

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	ceri
GH_PROJECT=	bsdinfo
GH_TAGNAME=	659abc7

PLIST_FILES=	bin/bsdinfo \
		bin/bsdinfon \
		man/man1/bsdinfo.1.gz

.include <bsd.port.mk>
